apiVersion: v1
kind: PersistentVolume
metadata:
    name: block-pv
spec:
    storageClassName: manual
    capacity:
        storage: 3Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /tmp/data
