apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-server
    dev: dev
  name: nginx-server
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-server
      env: dev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-server
        env: dev
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
