apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-app-v1
  name: blue-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app-v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-app-v1
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
