apiVersion: v1
kind: Service
metadata:
  name: canary-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    deptype: canary
status:
  loadBalancer: {}
