apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: recreate-strategy
  name: recreate-strategy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recreate-strategy
  strategy: 
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: recreate-strategy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
