apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: canary-app-v2
  name: canary-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-app-v2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: canary-app-v2
        deptype: canary
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
