apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-app-v2
  name: green-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app-v2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-app-v2
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 80
        resources: {}
status: {}
