apiVersion: v1
kind: Pod
metadata:
    name: pod-context
spec:
    securityContext:
        runAsUser: 1000
        runAsGroup: 3000
    containers:
    - name: sec-ctx-demo
      image: busybox
      command: ["sh", "-c", "sleep 1h"]
