apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: frontend
    business: store
  name: frontend
spec:
  containers:
  - image: nginx
    name: frontend
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
